### PR TITLE
fix plugin id

### PR DESCRIPTION
**Pull request by chr4ss1**
I fixed the ID of plugin, I assume it's mistake - they can't co-exist at the same time currently.

### CODE REVIEW

**Comment by dpa99c** [comment]
Oops, yeah thanks, missed that. I hadn't installed both in the same project, so hadn't noticed. Will push out in a patch release.

**Comment by dpa99c** [comment]
published to npm as v0.0.2

**Comment by chr4ss1** [comment]
how would I install it through npm/git? I would like to install [v10] of this library while having that bugfix.

**Comment by dpa99c** [comment]
`cordova plugin add https://github.com/dpa99c/cordova-android-play-services-gradle-release#v10`

**Comment by chr4ss1** [comment]
ah ok so you already merged it in the branches as well, thanks.

**Pull request merged**
